apiVersion: v1
kind: Service
metadata:
  name: uber-ui
spec:
  selector:
    app: uber-ui
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000 #target port is the container port
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-ui
spec:
  selector:
    matchLabels:
      app: uber-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: uber-ui
    spec:
      containers:
      - name: uber-ui
        image: 486636253131.dkr.ecr.eu-west-2.amazonaws.com/platformautomationaws-ecr:latest
        ports:
        - containerPort: 5000
